language: python

python:
    - "3.7"
    - "nightly"

install:
    - pip install -r requirements.txt

before_script:
    - flake8 ./code/ --ignore=F811,W504

script:
    - py.test ./code/ --doctest-modules

